# Site settings
title: GVillalta 99 thoughts
email: gvillalta99@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My thoughts on coding, science and politics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gvillalta99.github.io" # the base hostname & protocol for your site
twitter_username: gvillalta99 
github_username: gvillalta99 

# Build settings
markdown: kramdown
